import java.util.*;
import static myutils.Skrocenie_Print.print;

public class zad3_11 {
	public static void main(String[] args){
		int i = 0x80000000;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
		print(Integer.toBinaryString(i));
		i >>= 1;
}}
