import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import static myutils.Skrocenie_Print.*;
/*
Exercise 3: (4) Write a method that creates and initializes a two dimensional array of
double. The size of the array is determined by the arguments of the method, and the
initialization values are a range determined by beginning and ending values that are also
arguments of the method. Create a second method that will print the array generated by the
first method. In main( ) test the methods by creating and printing several different sizes of
arrays.
*/
public class Zad16_3 {
    public double[][] tworcatablic(int a, int b, int c, int d) {
        double[][] g;
        g = new double[a][b];
        for (int i = 0; i < a; i++) { //pętla która umożliwia przechodzenie po każdym wierszu tabeli dwuwymiarowej (zewnętrzne tablice)
            for (int j = 0; j < b; j++) // pętla, która umożliwia przechodzenie po każdym elemencie z danych wierszy i. Uwarunkowana wielkością tablic wewnętrznych z pomoca parametru b (wewnętrzne tablice). Musi być uruchomiona wewnątrz pętli przechodzącej po zewnętrznych tablicach aby zadziałało.
                g[i][j] = (double) ThreadLocalRandom.current().nextInt(c, d + 1); // losuje int z zakresu c-d i rzutuje go na double dzięki czemu wartości są 1.0, 3.0 itd
        }
        return g;
    }
    public void printeks(double[][] f) {
        println(Arrays.deepToString(f));
    }
    public static void main (String[] args) {
        Zad16_3 d = new Zad16_3();
        d.printeks(d.tworcatablic(4,5,1,12));
        d.printeks(d.tworcatablic(1,3,1,12));
        d.printeks(d.tworcatablic(6,5,1,12));
        d.printeks(d.tworcatablic(7,4,1,12));
        d.printeks(d.tworcatablic(3,4,1,12));

}
}